name: Build and push the Docker image

on:
  release:
    types: [created]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        uses: actions/github-script@v6
        id: set-version
        with:
          result-encoding: string
          script: return context.payload.release.tag_name.replace('v', '')

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/Robin-Sch/discord-template:latest
            ghcr.io/Robin-Sch/discord-template:${{ steps.set-version.outputs.result }}